### ISSUE TITLE
generalise determinand.control to allow for weighted sum

### ISSUE THREAD

**Issue by RobFryer** [osparcomm/HARSAT#373]
The TEQ is a weighted sum and currently has it's own bespoke function.  This can be incorporated into the sum function and thus reduce the number of bespoke functions necessary.  It will then be usable with any TEQ (currently only works for the WHO DFP).

**Comment by annelaerkes** [comment]
@RobFryer 
This seems to be the same issue as #470? Maybe we can close this one down (or merge it with #470 if that is possible)?

**Comment by RobFryer** [comment]
Closed as being dealt with in #470
