### ISSUE TITLE
Generate PDF of current documentation for checking by AMAP, HELCOM, OSPAR

### ISSUE THREAD

**Issue by hansmy** [osparcomm/HARSAT#396]
From PSG meeting: Generate PDF version of current documentation before Xmas if possible for checking by AMAP, HELCOM, OSPAR prior to January release

**Comment by morungos** [comment]
Well, in theory I can generate a manual (without vignettes) -- what is much harder is generating a PDF from `pkgdown` or something that includes all the many many pages on the web site. I can generate a PDF manual in traditional R terms. Possibly. Let me see. There are all sorts of weird TeX dependencies in the way of making PDFs work. This might not have been the easiest thing to commit to.

**Comment by morungos** [comment]
I am not sure this is doable in a realistic way. The manual is achievable, but omits vignettes. Some pages, such as the citation page, don't have a source and are only on the web site. `pkgdown` is very specifically for web sites.

The only way I can think of doing this is to manually print every single page to PDF and then concatenate them. It's a huge waste of time.

**Comment by morungos** [comment]
What I can offer is: (a) the manual, which is basically the reference sections, and (b a print to PDF of all the vignettes, concatenated into one large PDF file, more or less. Will that do? 

It is not complete documentation, but I have more pressing tasks than manually printing out what is getting close to 100 web pages and then glueing them together.

**Comment by morungos** [comment]
Okay, this is as good as I can reasonably get. It's 24Mb, so I won't email. I'll link here.
[merged.pdf](https://github.com/osparcomm/HARSAT/files/13665275/merged.pdf)

**Comment by morungos** [comment]
Closing as the doc is merged and the email sent.
