### ISSUE TITLE
Add in extra plot functionality needed for OSPAR assessments: auxiliary data plot, ratio plots, related time series plots.

### ISSUE THREAD

**Issue by hansmy** [osparcomm/HARSAT#409]
Initial release (January): already include functionality for reporting using function report_assessment. this currently produce meta-data, trend graph and data graph (also available with plot_assessment) and lay interpretation.
	
Issue for the February release: Add in extra functionality required for OSPAR assessment. This includes plot of auxiliary data, ratio plots, and plots of related time series.

**Comment by RobFryer** [comment]
Some of this functionality is also required to complete #140
