### ISSUE TITLE
The symbology in the summary tables generic, applicable to all situations

### ISSUE THREAD

**Issue by hansmy** [osparcomm/HARSAT#411]
To temporarily remove the symbology from the summary tables for the initial release.  Note there is still some work/ thinking to make it fully generic, and thus to be safe, the current symbology could be omitted until further, than using presenting symbols that work most of the time.

**Comment by morungos** [comment]
After discussion with @swamap, I'd suggest that symbology is, for now, retained but deprecated. One solution would be to add a new parameter, `symbology`, defaulting to `FALSE`, that, if true, maintains the output as it stands today. This would allow users (such as, maybe, @HansMJ) who *might* be depending on the symbology to continue using the package without loss until the new fully generic system is implemented.

**Comment by hansmy** [comment]
The solution to add a new parameter, symbology, defaulting to FALSE, that, if true, maintains the output as it stands today. Agreed, this sounds like a very good interim solution, let us do that.

**Comment by RobFryer** [comment]
I'll take this on and have a look at it today / tomorrow
