### ISSUE TITLE
Add/ update functionality for biological effects (including imposex) for OSPAR assessments

### ISSUE THREAD

**Issue by hansmy** [osparcomm/HARSAT#412]
Finalise functionality on biological effects, including imopsex. 

Some of these issues have been resolved in most recent pull requests. However, a few more changes are still needed in the context of this years's OSPAR assessment. 

Thus, to finalise changes needed for the OSPAR assessment to be commenced with the February release.

**Comment by RobFryer** [comment]
closing this and opening up a new series of issues to deal specifically with imposex (ordinal data)
