### ISSUE TITLE
bug with sum of TEQ

### ISSUE THREAD

**Issue by annelaerkes** [osparcomm/HARSAT#460]
There is a problem with naming the variable when doing weighted sum (inckuding TEFs) for dioxins. Currently we cannot chose a general name because the name is hardcoded to TEQDFP. We would like to be able to choose different names and do weighted sums of subsets of the PCDD/F and dl-PCBs. Need to generalize to weigthed sum of any subset.
The harcoded TEQDFP is found in the import_functions.R, look for "determinand.link.TEQdfp"

**Comment by annelaerkes** [comment]
Would it be a solution to add a specific "sumTEQ" reference in the import_function.R (line 2549) instead of having the TEQ calculation be part of "bespoke"? Then "sumTEQ" could cover various types of TEQ calculations (with all or a subset of the PCDD/F and dl-PCB substances).

**Comment by annelaerkes** [comment]
I have been trying to solve this issue: 
In import_functions.R (line 2550) I added an additional parameter "TEQsum" in addition to replace, sum and bespoke and in line 3567 I renamed TEQDFP to "TEQsum". I kept the hardcoded unit, group and pargroup (line 3628->). This allows for flexibility when defining TEQsums: you can have multiple different sums and name the variable as you like in the "information" input file. From the checks I have done so far, these changes seems to work as intended.
However, this is where I am stuck:
1) When plotting my new defined TEQsums, the title includes "DFP" (example "WHO-TEQ (DFP) conecntration"). I don't understand where the "DFP" comes from. I have been searching and searching but can't figure out the origin. Maybe it is fine it is there, but currently there is nothing on the figure that sepperates two different TEQsum variables from each other, which would be useful.
2) in the "import_check_functions.R" there are two references to "TEQDFP", which should refer to TEQsum or be outcommented (around line 508-521). The reference in line 515 feels redundant since we hardcode that information in the "import_functions.R" but is probably a check that was added for a reason. The reference in line 508 I am not sure how to rewrite to refer to TEQsum instead.

**Comment by RobFryer** [comment]
@annelaerkes 
Once you've got `determinand.link.weights` working and integrated via a pull request, it should be straightforward to merge it with `determinand.link.sum` so that there is only one function which does both.
I've just been looking through them, and the two functions are mostly the same, but `determinand.link.sum` has some bits that are tighter than `determinand.link.weights` and vice versa.
Perhaps easiest if we have another Teams chat and we can talk it through.  I might try to mark something up so we have something to talk to.

**Comment by annelaerkes** [comment]
@RobFryer 
Great, I have determinand.link.weights working now and will commit and pull it this afternoon

**Comment by RobFryer** [comment]
@annelaerkes 
Perfect.  I've got meetings at various points this pm, but will review as soon as I can.  
I've attached a work-up of the changes needed to merge the two functions
[determinand.link.sum changes.txt](https://github.com/osparcomm/HARSAT/files/15468238/determinand.link.sum.changes.txt)
