### ISSUE TITLE
OCDF environmental TEF value documentation question

### ISSUE THREAD

**Issue by annelaerkes** [osparcomm/HARSAT#462]
The OCDF environmental TEF value is hardcoded into the code as "CDFO = 0.00003". The documentation on OHAT only refers to the Human health TEFs which has a OCDF TEF of 0.0003. Can we verify that there exist documentation for the environmental OCDF TEF? Or is it an error and the environmental and humna health TEFs should be the same for all TEFs?

**Comment by RobFryer** [comment]
@annelaerkes Did we resolve this with Martin at the HARSAT workshop?  I

**Comment by annelaerkes** [comment]
@RobFryer 
I will double check with Martin - I think he agreed with me, but just to be sure

**Comment by RobFryer** [comment]
@annelaerkes @mml-BIOS-au 
Brendan sent me the Van den Berg reference from 2006 which is where the trail always leads to.  So unless Martin can uncover anything else, we will create a single set of TEFs for dioxin (like) compounds.  
We can discuss this when we chat soon.  I want to put in some warning messages for both this and #470 saying that the old code (which we need to keep for the next release for the OSPAR 2024 assessment) will be deprecated in the release that follows.

**Comment by mml-BIOS-au** [comment]
Hi Rob,

I have been roaming around and cannot seem to find any evidence of the 10 times lower OCDF for environment. The Canadian document from Brendan is from 2001 so only refers to the "old" WHO TEF 1998.

I also looked in the EU EQS dossier, but here there are no mention of a secondary poisoning specific TEF for OCDF either.

So I will support a single set of TEFs for dioxin!

Martin

Fra: RobFryer ***@***.***>
Sendt: 4. juni 2024 14:23
Til: osparcomm/HARSAT ***@***.***>
Cc: Martin Mørk Larsen ***@***.***>; Mention ***@***.***>
Emne: Re: [osparcomm/HARSAT] OCDF environmental TEF value documentation question (Issue #462)


@annelaerkes<https://github.com/annelaerkes> @mml-BIOS-au<https://github.com/mml-BIOS-au>
Brendan sent me the Van den Berg reference from 2006 which is where the trail always leads to. So unless Martin can uncover anything else, we will create a single set of TEFs for dioxin (like) compounds.
We can discuss this when we chat soon. I want to put in some warning messages for both this and #470<https://github.com/osparcomm/HARSAT/issues/470> saying that the old code (which we need to keep for the next release for the OSPAR 2024 assessment) will be deprecated in the release that follows.

-

**Comment by RobFryer** [comment]
This has been resolved in #474
